version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ec2eventlogs"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ophpc17rkl8x"
s3_prefix = "ec2eventlogs"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
